name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'
  schedule:
    - cron: '15 6,18 * * *'
  workflow_dispatch:

jobs:
  docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: https://github.com/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: https://github.com/actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1
        id: get-latest-tag
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

      - name: Checkout Repo
        uses: https://github.com/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

      - name: Generate tags
        id: meta
        uses: https://github.com/docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            docker.io/ricariel/${{ vars.IMAGE_NAME }}
            git.zyria.de/pyrox/${{ vars.IMAGE_NAME }}
          tags: |
            #type=schedule,pattern=${{ steps.get-latest-tag.outputs.tag }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ steps.get-latest-tag.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.get-latest-tag.outputs.tag }}
            type=semver,pattern={{major}},value=${{ steps.get-latest-tag.outputs.tag }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - if: github.event_name != 'pull_request'
        name: Log in to docker.io
        uses: https://github.com/docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - if: github.event_name != 'pull_request'
        name: Log in to zyria.de
        uses: https://github.com/docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ZYRIA_TOKEN }}
          registry: git.zyria.de

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Build Image
        id: build-image
        uses: https://github.com/docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          provenance: true
          sbom: true
          platforms: ${{ vars.PLATFORMS }}
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Docker Hub Description
        uses: https://github.com/peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ricariel/${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          enable-url-completion: true
