name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'
  schedule:
    - cron: '15 6,18 * * *'
  workflow_dispatch:

jobs:
  docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: https://github.com/actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1
        id: get-latest-tag
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

      - name: Checkout Repo
        uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}

      - name: Generate tags
        id: meta
        uses: https://github.com/docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: |
            docker.io/ricariel/${{ vars.IMAGE_NAME }}
            git.zyria.de/pyrox/${{ vars.IMAGE_NAME }}
          tags: |
            #type=schedule,pattern=${{ steps.get-latest-tag.outputs.tag }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ steps.get-latest-tag.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.get-latest-tag.outputs.tag }}
            type=semver,pattern={{major}},value=${{ steps.get-latest-tag.outputs.tag }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - if: github.event_name != 'pull_request'
        name: Log in to docker.io
        uses: https://github.com/docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - if: github.event_name != 'pull_request'
        name: Log in to zyria.de
        uses: https://github.com/docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ZYRIA_TOKEN }}
          registry: git.zyria.de

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build Image
        id: build-image
        uses: https://github.com/docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47 # v6
        with:
          context: .
          provenance: true
          sbom: true
          platforms: ${{ vars.PLATFORMS }}
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Docker Hub Description
        uses: https://github.com/peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ricariel/${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          enable-url-completion: true
