---
on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: mkdir -p dist/release
      - run: touch dist/release/NOASSETS
      - uses: https://code.forgejo.org/actions/forgejo-release@6e3a26f82af465c93109eaf82c021493f5b36199 # v2.11.0
        with:
          direction: upload
          url: https://git.zyria.de
          token: ${{ secrets.ZYRIA_TOKEN }}
