---
on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: https://code.forgejo.org/actions/forgejo-release@v1
        with:
          direction: upload
          url: https://git.zyria.de
          release-dir: dist/release
          token: ${{ secrets.ZYRIA_TOKEN }}
